### ISSUE TITLE
Add Linux command at the top

### ISSUE THREAD

**Issue by gordonwatts** [AtlasWHHV/Gen_Reco#1]
Add:

    #!/bin/bash

as the first line, and then make the file executable:

    chmod a+x generator_setup.sh

Then you can type:

    ./generator_setup.sh

from the command line and it will execute in bash no matter the shell it is called from. Also, if someone cat's the file they can see that it is mention to execute in bash (and you don't have to specify).

**Comment by zhilothebest** [comment]
I will make this change, but out of curiosity, whats the difference between writing:

` ./generator_setup.sh`

 to

`sh generator_setup.sh`

within shell or bash??

**Comment by gordonwatts** [comment]
There is no difference, other than it is "cool". ;-)

Actually, there is one. Now encoded in the script is the flavor of the shell it was written in, so now when people look at it later they will know what you meant and even if their fav shell is zsh they will know to use bash.
