### ISSUE TITLE
Remove specific root setup

### ISSUE THREAD

**Issue by gordonwatts** [AtlasWHHV/Gen_Reco#2]
I believe the asetup command will wipe out any specific root setup anyway.

Also, you don't care about root setup. If you depend on that specific version of root (with the TMVA stuff in it) for even generation, then something scary has gone wrong. :-)

**Comment by zhilothebest** [comment]
Its been commented out.

**Comment by zhilothebest** [comment]
Actually, it seems that a lot of the ATLAS_LOCAL_ROOT_BASE is requiring your specific root setup, so I dont think we can comment it out.

**Comment by gordonwatts** [comment]
You need it only for that first setup. But ATLAS has normalized how it installs everything (it is all cvmfs based now), so you can just hardwire it to that one location.

**Comment by zhilothebest** [comment]
Since we are doing the Parathesis subprocess thing, shouldnt we need it twice then?

**Comment by gordonwatts** [comment]
As you have it now is perfect.
