### ISSUE TITLE
Extract the ATLAS lines you need from configASetup.sh

### ISSUE THREAD

**Issue by gordonwatts** [AtlasWHHV/Gen_Reco#4]
There is actually only one line you need from there - extract it.

This line introduces a dependency - which is basically requiring "setupATLAS". You could even remove it totally and then print out "You must do setupATLAS before you run this script" if you want.

**Comment by zhilothebest** [comment]
What specific line are you talking about? Did you mean the asetup? Because if so, I found the alias and replaced it.

**Comment by gordonwatts** [comment]
Cool.

**Comment by zhilothebest** [comment]
So has this specific issue been resolved?

**Comment by gordonwatts** [comment]
Yes, current version looks good.
