### ISSUE TITLE
Why do you have local setup in one case, but not the other?

### ISSUE THREAD

**Issue by gordonwatts** [AtlasWHHV/Gen_Reco#5]
THis line:

    source $ATLAS_LOCAL_ROOT_BASE/user/atlasLocalSetup.sh

why dont' you have it in both places?

**Comment by zhilothebest** [comment]
Because I was running the asetup alias that your root setup had. Now im confused with whether to use 

`source $AtlasSetup/scripts/asetup.sh`

or 

`source $ATLAS_LOCAL_ROOT_BASE/user/atlasLocalSetup.sh`

@gordonwatts

**Comment by gordonwatts** [comment]
They do two different things. The first one setup the release for use, and the second setups the environment for various commands (like lsetup). So the second one is what is usually run in a user's login. The first one is what is usually run in by just typing "asetup" after the second script has been run.

I think what is in the script is fine, so I'll close this. re-open if it isn't clear.
