### ISSUE TITLE
After RECO, exit output is as follows. Is this what it is supposed to be?

### ISSUE THREAD

**Issue by zhilothebest** [AtlasWHHV/Gen_Reco#7]
`PyJobTransforms.main 2016-12-30 14:58:32,794 INFO /cvmfs/atlas.cern.ch/repo/sw/software/x86_64-slc6-gcc48-opt/20.1.8/AtlasReconstruction/20.1.8/InstallArea/share/bin/Reco_tf.py stopped at Fri Dec 30 14:58:32 2016, trf exit code 0
`

I was unable to find what trf exit code actually meant, just a bunch of pytransform codes.

**Comment by ghost** [comment]
https://docs.python.org/3.5/library/sys.html#sys.exit

Yeah, it's normal.  Not an error.  And here you can find the Generate_tf.py file and you can have a look at lines 100-107 where this is occurring:

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwixv-3ix57RAhVP1WMKHQIXDkkQFggfMAE&url=https%3A%2F%2Flost-contact.mit.edu%2Fafs%2Fcern.ch%2Fatlas%2Fsoftware%2Fbuilds%2FAtlasProduction%2F17.2.14.3%2FInstallArea%2Fpython%2FEvgenJobTransforms%2FGenerate_tf.py&usg=AFQjCNE5hNin-nvw2a1jhs45-FbX6gjnlw&bvm=bv.142059868,d.cGc&cad=rja

**Comment by zhilothebest** [comment]
Hmm interesting way it works. But its a good assumption (hopefully) that it works for reco as well? excellent find ! Ill mark this as clsoed!

**Comment by gordonwatts** [comment]
A zero exit code on Linux means "successful". :-) In general, get nervous when that number isn't zero.
